import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { HomePage } from "./components/HomePage";
import { RequestFormPage } from "./components/RequestFormPage";
import { AdminPage } from "./components/AdminPage";
import { Toaster } from "./components/ui/sonner";
export default function App() { const [currentPage, setCurrentPage] = useState("home"); const [submissions, setSubmissions] = useState([]); const handleRequestClick = () => { setCurrentPage("request"); window.scrollTo(0, 0); }; const handleAdminClick = () => { setCurrentPage("admin"); window.scrollTo(0, 0); }; const handleBackToHome = () => { setCurrentPage("home"); window.scrollTo(0, 0); }; const handleFormSubmit = (formData) => { setSubmissions([...submissions, formData]); }; return (_jsxs("div", { className: "min-h-screen flex flex-col", children: ["      ", currentPage === "home" && (_jsxs(_Fragment, { children: ["          ", _jsx(Header, { onContactClick: handleRequestClick }), "          ", _jsxs("main", { className: "flex-1", children: ["            ", _jsx(HomePage, { onRequestClick: handleRequestClick }), "          "] }), "          ", _jsx(Footer, {}), "          ", "          ", _jsx("button", { onClick: handleAdminClick, className: "fixed bottom-4 right-4 w-12 h-12 rounded-full bg-primary text-primary-foreground shadow-lg hover:bg-primary/90 flex items-center justify-center opacity-50 hover:opacity-100 transition-opacity", title: "\uAD00\uB9AC\uC790 ?\uFFFD\uC774\uC9C0", children: "            ?\uFFFD\uFFFD          " }), "        "] })), "      ", currentPage === "request" && (_jsx(RequestFormPage, { onBack: handleBackToHome, onSubmit: handleFormSubmit })), "      ", currentPage === "admin" && (_jsx(AdminPage, { onBack: handleBackToHome, submissions: submissions })), "      ", _jsx(Toaster, {}), "    "] })); }
